'''
Created on 13-Sep-2025

@author: admin
'''
print(2+3)
print(4*3)

try:
   
    print(9/"v")
    

except Exception as e:
    print("Error occured in Line 9:", e, type(e))
    # print(9/0)
print(7-2)